# Generated by Django 5.2.15 on 2026-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('HOTEL_OWNER', 'Hotel Owner')], default='CUSTOMER', max_length=20),
        ),
    ]
