# Generated by Django 5.2.15 on 2026-06-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
