# Generated by Django 5.2.15 on 2026-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash On Arrival')], default='CASH', max_length=20),
        ),
    ]
